source 'https://rubygems.org'
ruby '2.1.3'
gem 'rails', '~> 4.2.0.beta2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'multi_json'
gem 'yajl-ruby', require: 'yajl'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'bootstrap-sass'
gem 'sass-rails', '5.0.0.beta1'
gem 'autoprefixer-rails'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-slider-rails'
gem 'bootstrap-kaminari-views'
gem 'date_validator'
gem 'jquery-validation-rails'
gem 'devise'
gem 'devise_invitable'
gem 'rack-tracker'
gem 'devise-async'
gem 'mailboxer', :git => 'git://github.com/div/mailboxer.git', :branch => 'rails42-foreigner'
# gem 'mailboxer'
gem 'jquery-datatables-rails', '~> 3.1.1'
gem 'ajax-datatables-rails', '~> 0.3.0'
gem 'responders', '~> 2.0'
gem 'figaro', '>= 1.0.0.rc1'
gem 'geocoder'
gem 'seedbank'
gem 'font-awesome-rails'
gem 'newrelic_rpm'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'high_voltage'
gem 'aasm'
gem 'kaminari'
gem 'pg'
gem 'pg_search'
gem 'active_attr'
gem 'going_postal'
gem 'phony_rails'
gem 'sidekiq'
gem 'sinatra', '>= 1.3.0', :require => nil
gem 'paperclip', '~> 4.1', github: 'thoughtbot/paperclip'
gem 'aws-sdk'
gem 'paperclip-aws'
gem 'delayed_paperclip'
gem 'rmagick'
gem 'sendgrid'
gem 'simple_form', '~> 3.1.0.rc1', github: 'plataformatec/simple_form', branch: 'master'
gem 'unicorn'
gem 'unicorn-rails'
gem 'faker'
group :development do
  gem 'letter_opener', group: :development
  gem 'railroady'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
end
group :development, :test do
  gem 'bullet'
  gem 'derailed_benchmarks'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :production, :staging do
  gem 'rails_12factor'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
